# Triggering schedule activation

name: Check Appointments

on:
  schedule:
    - cron: "*/5 * * * *"  # 每5分钟运行一次（GitHub 不支持30秒间隔）
  #workflow_dispatch:       # 允许你手动点击运行

jobs:
  run-script:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
